### ISSUE TITLE
[Guide] mkimage line is incorrect

### ISSUE THREAD

**Issue by xnopasaranx** [K-arch27/pinebtrfs#1]
I already made a PR for you on the snaptest branch, which is now gone, so here is an issue instead:
```mkimage -A arm -O linux -T script -C none -n "U-Boot boot script" -d /mnt/@/boot.txt /mnt/@/boot.scr```
does not work, since that path doesn't exist. We have remounted to /mnt and thus I assume the correct command is:
```mkimage -A arm -O linux -T script -C none -n "U-Boot boot script" -d /mnt/boot/boot.txt /mnt/boot/boot.scr```  as that is the only directory containing those bootfiles and where the boot volume is actually mounted. Anyway, this is what I have been doing to get the correct boot.scr

**Comment by K-arch27** [comment]
The line is actually correct.

  	btrfs subvolume set-default $(btrfs subvolume list /mnt | grep "@/.snapshots/1/snapshot" | grep -oP '(?<=ID )[0-9]+') /mnt
  	
this set the default subvolume to be automatically mounted on next mount , and we umount and re-mount it in the process thus making the path /mnt/boot/boot.txt be the right path
 
So the guide is only wrong if you don't follow it up fully ;)

**Comment by K-arch27** [comment]
That line was intended for the old Version when we didn't change the default sub-volume 
then the path was /mnt/@/boot/boot.txt  (guess I still missed a boot in there , But now that branch as since been closed)
