### ISSUE TITLE
[Guide] Information missing about mkinitcpio

### ISSUE THREAD

**Issue by xnopasaranx** [K-arch27/pinebtrfs#2]
I am pretty sure, that this guide will leave people with an unbootable system. You have to rebuild your linux kernel image after all of these changes, otherwise it will fail to boot with and unknown filesystem type error. On arch you would chroot into the new filesystem, but this is not possible from a PC, because of the different architectures. I had to boot the phone from an arch sd install, remount all of the newly created btrfs structure, then chroot into that and run "mkinitcpio -p linux-megi" from there.

A warning would be appropriate, in case someone with no prior arch/chroot experience attempts this!

**Comment by K-arch27** [comment]
Never had to do this , but I added a Line about regenerating the Initramfs
